### ISSUE TITLE
Version 2.0 Checklist

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#1040]
- [x] FAQ updated with all related issues
- [x] json schema push to repo or ref here
- [x] Upgrade Creator EE to ansible 2.12.4 final
